FROM jupyter/tensorflow-notebook:2ce7c06a61a1

LABEL maintainer="Elias Youssef - https://github.com/nettoyoussef/science-reproducibility"

EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/home"]


